//Handle for CsvParser Data to Wrapper List.
    public class RefundFileWrapper {
        //Columns for Wrapper data.
        public string strStartDate;
        public string strTrasactionDate;
        public string strCommunity;
        public string strClient;
        public string strTransactionId;
        public string strAdjustmentId;
        public string strTranctionType;
        public string strTransactionCurrency;
        public string strTransactionAmount;
        public string strSourceType;
        public string strSourceDetails;
        public string strDestinationType;
        public string strDestinationDetails;
        public string strParticipantType;
        public string strParticipantDetails;
        public string strParticipantsink;
        public string strOriginalCurrency;
        public string strOriginalAmount;
        public string strParticipantCurrency;
        public string strParticipiantAmount;
        public string strExchangeRate;
        public string strNonForexFee;
        public string strForexFee;
        public string strBalanceBefore;
        public string strBalanceAdjustement;
        public string strBalanceAfter;
        public string strStatus;
        public string strForexFlag;
        public string strDircetion;
        public string strExternalRef;
        public string strTransactionInfo;
        public string strScenarioCases;
        public string strSingleCases;

        public RefundFileWrapper() {
            strStartDate = '';
            strTrasactionDate = '';
            strCommunity = '';
            strClient = '';
            strTransactionId = '';
            strAdjustmentId = '';
            strTranctionType = '';
            strTransactionCurrency = '';
            strTransactionAmount = '';
            strSourceType = '';
            strSourceDetails = '';
            strDestinationType = '';
            strDestinationDetails = '';
            strParticipantType = '';
            strParticipantDetails = '';
            strParticipantsink = '';
            strOriginalCurrency = '';
            strOriginalAmount = '';
            strParticipantCurrency = '';
            strParticipiantAmount = '';
            strExchangeRate = '';
            strNonForexFee = '';
            strForexFee = '';
            strBalanceBefore = '';
            strBalanceAdjustement = '';
            strBalanceAfter = '';
            strStatus = '';
            strForexFlag = '';
            strDircetion = '';
            strExternalRef = '';
            strTransactionInfo = '';
            strScenarioCases = '';
            strSingleCases = '';
        }

    }