@isTest
private class Test_submissionservice{
    @isTest
    private static void submissionserviceTestMethord1(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

        a55.DownloadFile(a26);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord2(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


        a55.ListResources('test',True);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord3(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


          a55.SubmitXML(a50);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord4(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


        a55.RegisterResource(a26,'test',True,True);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord5(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

          a55.DeleteResource('test','sample',True);

        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord6(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

        a55.UploadFileAppend('test',a26);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord7(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


        a55.ConvertFile(a26,a18);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord8(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        a16.transportName = 'TestName';
        a16.recipientType = 'TestType';
        a16.transportIndex = 'TestInd';
        a16.nVars = 123;
        a16.nSubnodes = 567;
        a16.nAttachments = 908;
        
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

        a55.SubmitTransport(a16);
      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord9(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        a43.nItems = 123;
        a43.fullPreviewMode = True;
        a43.attachmentFilter = 'TestFilter';
        a43.outputFileMode = 'TestOut';
        a43.includeSubNodes = True;
        a43.startIndex = 'TestInd';
        
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


        a55.ExtractNext(a43);
    

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord10(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();


          a55.RetrieveResource('Test','Test1',True,'Test3');    

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord11(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

   
        a55.ExtractFirst(a11,a15,a43);

      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord12(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

       // a55.DownloadFile(a26);
      //  a55.ListResources('test',True);
      //  a55.SubmitXML(a50);
      //  a55.RegisterResource('test');
     //   a55.DeleteResource('test','sample',True);
     //   a55.UploadFileAppend(a26);
     //   a55.ConvertFile();
      //  a55.SubmitTransport(a25);
      //  a55.ExtractNext(a12);
      //  a55.RetrieveResource('Test','Test1',True,'Test3');    
      //  a55.ExtractFirst(a12);
          a55.UploadFile('TestFile','TestName');
      //  a55.Submit(a25);
      
        }Catch(Exception e){}
    }
    @isTest
    private static void submissionserviceTestMethord13(){
     try{
        submissionservice sub = new submissionservice();
        submissionservice.transports_element trn = new submissionservice.transports_element();
        submissionservice.Attachment    a1  =   new submissionservice.Attachment();
        submissionservice.ExtractNextResponse_element   a2  =   new submissionservice.ExtractNextResponse_element();
        submissionservice.subNodes_element1 a3  =   new submissionservice.subNodes_element1();
        submissionservice.UploadFile_element    a4  =   new submissionservice.UploadFile_element();
        submissionservice.UploadFileResponse_element    a5  =   new submissionservice.UploadFileResponse_element();
        submissionservice.resources_element a6  =   new submissionservice.resources_element();
        submissionservice.SubmitTransportResponse_element   a7  =   new submissionservice.SubmitTransportResponse_element();
        submissionservice.DeleteResourceResponse_element    a8  =   new submissionservice.DeleteResourceResponse_element();
        submissionservice.subnodes_element  a9  =   new submissionservice.subnodes_element();
        submissionservice.ExtractFirst_element  a10 =   new submissionservice.ExtractFirst_element();
        submissionservice.BusinessData  a11 =   new submissionservice.BusinessData();
        submissionservice.ExtractionResult  a12 =   new submissionservice.ExtractionResult();
        submissionservice.RegisterResource_element  a13 =   new submissionservice.RegisterResource_element();
        submissionservice.vars_element  a14 =   new submissionservice.vars_element();
        submissionservice.BusinessRules a15 =   new submissionservice.BusinessRules();
        submissionservice.Transport a16 =   new submissionservice.Transport();
        submissionservice.UploadFileAppend_element  a17 =   new submissionservice.UploadFileAppend_element();
        submissionservice.ConversionParameters  a18 =   new submissionservice.ConversionParameters();
        submissionservice.RetrieveResource_element  a19 =   new submissionservice.RetrieveResource_element();
        submissionservice.SubmitTransport_element   a20 =   new submissionservice.SubmitTransport_element();
        submissionservice.Resources a21 =   new submissionservice.Resources();
        submissionservice.ExtractionHeader  a22 =   new submissionservice.ExtractionHeader();
        submissionservice.convertedAttachments_element  a23 =   new submissionservice.convertedAttachments_element();
        submissionservice.ConvertFile_element   a24 =   new submissionservice.ConvertFile_element();
        submissionservice.SubmissionResults a25 =   new submissionservice.SubmissionResults();
        submissionservice.WSFile    a26 =   new submissionservice.WSFile();
        a26.name = 'TestName';
        a26.mode = 'TestMode';
        a26.content = 'TestContent';
        a26.url = 'https://as1.ondemand.esker.com:443/EDPWS/EDPWS.dll?Handler=SubmissionHandler&Version=1.0';
        a26.storageID = 'abcdefgh';
        
        submissionservice.RetrieveResourceResponse_element  a27 =   new submissionservice.RetrieveResourceResponse_element();
        submissionservice.externalVars_element  a28 =   new submissionservice.externalVars_element();
        submissionservice.ListResourcesResponse_element a29 =   new submissionservice.ListResourcesResponse_element   ();
        submissionservice.DownloadFileResponse_element  a30 =   new submissionservice.DownloadFileResponse_element    ();
        submissionservice.multipleLongValues_element    a31 =   new submissionservice.multipleLongValues_element  ();
        submissionservice.attachments_element   a32 =   new submissionservice.attachments_element ();
        submissionservice.multipleDoubleValues_element  a33 =   new submissionservice.multipleDoubleValues_element    ();
        submissionservice.SubmitResponse_element    a34 =   new submissionservice.SubmitResponse_element  ();
        submissionservice.SubmitXML_element a35 =   new submissionservice.SubmitXML_element   ();
        submissionservice.ConvertFileResponse_element   a36 =   new submissionservice.ConvertFileResponse_element ();
        submissionservice.ExtractFirstResponse_element  a37 =   new submissionservice.ExtractFirstResponse_element    ();
        submissionservice.RegisterResourceResponse_element  a38 =   new submissionservice.RegisterResourceResponse_element    ();
        submissionservice.ExtractNext_element   a39 =   new submissionservice.ExtractNext_element ();
        submissionservice.SubmissionResult  a40 =   new submissionservice.SubmissionResult    ();
        submissionservice.SubmitXMLResponse_element a41 =   new submissionservice.SubmitXMLResponse_element   ();
        submissionservice.ListResources_element a42 =   new submissionservice.ListResources_element   ();
        submissionservice.ExtractionParameters  a43 =   new submissionservice.ExtractionParameters    ();
        submissionservice.SessionHeader a44 =   new submissionservice.SessionHeader   ();
        submissionservice.DownloadFile_element  a45 =   new submissionservice.DownloadFile_element    ();
        submissionservice.SubNode   a46 =   new submissionservice.SubNode ();
        submissionservice.Submit_element    a47 =   new submissionservice.Submit_element  ();
        submissionservice.DeleteResource_element    a48 =   new submissionservice.DeleteResource_element  ();
        submissionservice.transportIDs_element  a49 =   new submissionservice.transportIDs_element    ();
        submissionservice.XMLDescription    a50 =   new submissionservice.XMLDescription  ();
        submissionservice.multipleStringValues_element  a51 =   new submissionservice.multipleStringValues_element    ();
        submissionservice.Var   a52 =   new submissionservice.Var ();
        submissionservice.UploadFileAppendResponse_element  a53 =   new submissionservice.UploadFileAppendResponse_element    ();
        submissionservice.ConversionResult  a54 =   new submissionservice.ConversionResult    ();
        submissionservice.SubmissionServiceSoap a55 =   new submissionservice.SubmissionServiceSoap   ();

        //a55.Submit(a11,a15);
      
        }Catch(Exception e){}
    }
    
}