global class VirtualCard {
    global String cardName;
    global String state;
    global String cardBrand;
    global String cardNumber;
    global String cardholderName;
    global String availableBalance;
    global String actualBalance;
    global String cvv;
    global String expiryDateMonth;
    global String expiryDateYear;
    global String expiryPeriod;
    global String nameOnCard;
    global String startDateMonth;
    global String startDateYear;
    global String isDefault;
    global String cardReference;
    global String cardType;
    global String externalIdentifier;
    global String cardInfo;
    global String orderedCardInfo;
    global String transactionReference;
}